# Generated by Django 4.2.30 on 2026-08-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0008_solicitudclase_bloqueado_solicitudclase_intentos'),
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='clase.clase'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='ultimo_mensaje',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
