# Generated by Django 4.2.30 on 2026-08-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_conversacion_clase_alter_conversacion_ultimo_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='clase',
        ),
    ]
