# Generated by Django 4.2.30 on 2026-09-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0013_remove_clase_activo'),
        ('mensajeria', '0003_remove_conversacion_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='clase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversacion', to='clase.clase'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='tipo',
            field=models.CharField(choices=[('privada', 'Privada'), ('clase', 'Chat de clase')], default='privada', max_length=10),
        ),
    ]
