# Generated by Django 4.2.30 on 2026-07-17 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clase', '0002_actividad_calificacion_maxima_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Formulario')),
                ('descripcion', models.TextField(blank=True, verbose_name='Instrucciones o Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_ejercicios', to='clase.clase', verbose_name='Clase Asociada')),
            ],
            options={
                'verbose_name': 'Formulario de Ejercicios',
                'verbose_name_plural': 'Formularios de Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='EjercicioPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('tipo_respuesta', models.CharField(choices=[('unica', 'Selección Única (Solo una opción es correcta)'), ('multiple', 'Selección Múltiple (Varias opciones pueden ser correctas)')], default='unica', max_length=15, verbose_name='Tipo de Respuesta')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de visualización')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ejercicios.formularioejercicio')),
            ],
            options={
                'verbose_name': 'Pregunta de Ejercicio',
                'verbose_name_plural': 'Preguntas de Ejercicios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EjercicioOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255, verbose_name='Texto de la opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='ejercicios.ejerciciopregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
            },
        ),
    ]
