# Generated by Django 4.2.30 on 2026-07-17 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_actividad_calificacion_maxima_and_more'),
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='clase.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='preguntas_img/')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ejercicios.ejercicio')),
            ],
        ),
        migrations.RemoveField(
            model_name='ejerciciopregunta',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='formularioejercicio',
            name='clase',
        ),
        migrations.DeleteModel(
            name='EjercicioOpcion',
        ),
        migrations.DeleteModel(
            name='EjercicioPregunta',
        ),
        migrations.DeleteModel(
            name='FormularioEjercicio',
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='ejercicios.pregunta'),
        ),
    ]
