# Generated by Django 4.2.30 on 2026-06-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.TextField(verbose_name='Pregunta')),
                ('tipo', models.CharField(choices=[('OPCION_MULTIPLE', 'Selección Múltiple con Única Respuesta'), ('TEXTO', 'Texto Abierto / Escribir Respuesta')], default='OPCION_MULTIPLE', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Disponible para estudiantes'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='enunciado',
            field=models.TextField(verbose_name='Instrucciones o Enunciado'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen_contexto',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/contextos/'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del Ejercicio'),
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='ejercicios.ejercicio'),
        ),
    ]
