# Generated by Django 4.2.30 on 2026-07-27 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0003_intentoejercicio_respuestaestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentoejercicio',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
