# Generated by Django 4.2.30 on 2026-07-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0004_alter_intentoejercicio_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
