# Generated by Django 4.2.30 on 2026-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0005_ejercicio_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoejercicio',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
