# Generated by Django 4.2.30 on 2026-08-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0006_intentoejercicio_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='juego_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('imagen_quiz', 'Quiz con imagen'), ('juego', 'Juego'), ('texto', 'Texto'), ('verdadero_falso', 'Verdadero o Falso'), ('completar', 'Completar')], default='quiz', max_length=30),
        ),
    ]
