# Generated by Django 4.2.30 on 2026-08-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0007_ejercicio_contenido_ejercicio_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video_principal',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/videos/', verbose_name='Video principal'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video (YouTube, Vimeo)'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/', verbose_name='Imagen (opcional)'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('video_quiz', 'Video + Quiz'), ('juego', 'Juego'), ('texto', 'Texto'), ('verdadero_falso', 'Verdadero o Falso'), ('completar', 'Completar')], default='quiz', max_length=30),
        ),
    ]
