# Generated by Django 4.2.30 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0008_initial'),
        ('ejercicios', '0008_alter_ejercicio_options_ejercicio_video_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='recursos',
            field=models.ManyToManyField(blank=True, related_name='ejercicios', to='docente.recursomusical', verbose_name='Recursos adjuntos'),
        ),
    ]
