# Generated by Django 4.2.30 on 2026-09-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0009_ejercicio_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
