# Generated by Django 4.2.30 on 2026-09-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0010_ejercicio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='config_auditivo',
            field=models.JSONField(blank=True, help_text='JSON con tipo, dificultad, número de preguntas, etc.', null=True, verbose_name='Configuración de entrenamiento auditivo'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('video_quiz', 'Video + Quiz'), ('juego', 'Juego'), ('texto', 'Texto'), ('verdadero_falso', 'Verdadero o Falso'), ('completar', 'Completar'), ('entrenamiento_auditivo', 'Entrenamiento Auditivo')], default='quiz', max_length=30),
        ),
        migrations.CreateModel(
            name='PracticaAuditiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_practica', models.CharField(choices=[('intervalos', 'Intervalos'), ('acordes', 'Acordes'), ('notas', 'Notas individuales'), ('ritmo', 'Ritmo'), ('melodia', 'Melodía')], max_length=30)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('total_preguntas', models.PositiveIntegerField(default=0)),
                ('tiempo_promedio_seg', models.FloatField(default=0)),
                ('detalle_respuestas', models.JSONField(default=list, help_text='Lista con cada respuesta: {pregunta, respuesta, correcta, tiempo}')),
                ('intento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practica_auditiva', to='ejercicios.intentoejercicio')),
            ],
        ),
    ]
