# Generated by Django 4.2.30 on 2026-09-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ejercicios', '0011_ejercicio_config_auditivo_alter_ejercicio_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticaLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_practica', models.CharField(choices=[('intervalos', 'Intervalos'), ('acordes', 'Acordes'), ('notas', 'Notas individuales'), ('ritmo', 'Ritmo'), ('melodia', 'Melodía')], max_length=30)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=20)),
                ('instrumento', models.CharField(default='piano', max_length=30)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('total_preguntas', models.PositiveIntegerField(default=0)),
                ('detalle_respuestas', models.JSONField(default=list)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas_libres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Práctica libre',
                'verbose_name_plural': 'Prácticas libres',
                'ordering': ['-fecha'],
            },
        ),
    ]
