# Generated by Django 4.2.30 on 2026-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0012_practicalibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalibre',
            name='subtipo',
            field=models.CharField(choices=[('basico', 'Básico'), ('inversiones', 'Con inversiones'), ('cifrado', 'Cifrado americano'), ('progresiones', 'Progresiones armónicas')], default='basico', help_text='Subtipo para acordes avanzados', max_length=30),
        ),
    ]
