# Generated by Django 4.2.30 on 2026-09-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0013_practicalibre_subtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('video_quiz', 'Video + Quiz'), ('juego', 'Juego'), ('texto', 'Texto'), ('verdadero_falso', 'Verdadero o Falso'), ('completar', 'Completar'), ('entrenamiento_auditivo', 'Entrenamiento Auditivo'), ('entrenamiento_avanzado', 'Entrenamiento Avanzado')], default='quiz', max_length=30),
        ),
        migrations.AlterField(
            model_name='practicaauditiva',
            name='tipo_practica',
            field=models.CharField(choices=[('intervalos', 'Intervalos'), ('acordes', 'Acordes'), ('notas', 'Notas individuales'), ('ritmo', 'Ritmo'), ('melodia', 'Melodía'), ('oido_absoluto', 'Oído Absoluto'), ('oido_relativo', 'Oído Relativo'), ('tapping_ritmico', 'Tapping Rítmico'), ('dictado_melodico', 'Dictado Melódico')], max_length=30),
        ),
    ]
