# Generated by Django 4.2.30 on 2026-09-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0014_alter_ejercicio_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('video_quiz', 'Video + Quiz'), ('acorde', 'Acordes'), ('acordes', 'Acordes (Módulo)'), ('intervalos', 'Intervalos'), ('escalas', 'Escalas'), ('texto', 'Texto'), ('verdadero_falso', 'Verdadero o Falso'), ('completar', 'Completar'), ('entrenamiento_auditivo', 'Entrenamiento Auditivo'), ('entrenamiento_avanzado', 'Entrenamiento Avanzado')], default='quiz', max_length=30),
        ),
    ]
