# Generated by Django 4.2.30 on 2026-07-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
