# Generated by Django 4.2.30 on 2026-08-21 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0007_ejercicio_contenido_ejercicio_imagen_principal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudiante', '0003_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
            ],
        ),
        migrations.AlterField(
            model_name='respuestaestudiante',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_estudiantes_preguntas', to='ejercicios.pregunta'),
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_ejercicio', to='ejercicios.ejercicio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
