# Generated by Django 4.2.30 on 2026-08-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_perfil_alter_respuestaestudiante_pregunta_intento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(default='estudiante', max_length=20),
            preserve_default=False,
        ),
    ]
