# Generated by Django 4.2.30 on 2026-06-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_perfil_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('portada', models.ImageField(blank=True, null=True, upload_to='cursos/portadas/')),
                ('url_portada_respaldo', models.URLField(blank=True, help_text='Por si usas links de Unsplash')),
                ('nivel', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20)),
                ('categoria', models.CharField(choices=[('teoria', 'Teoría Musical'), ('auditivo', 'Entrenamiento Auditivo'), ('instrumento', 'Instrumento')], default='teoria', max_length=20)),
                ('duracion_horas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField(help_text='Qué se enseñará en este módulo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='web.curso')),
            ],
        ),
    ]
