# Generated by Django 4.2.30 on 2026-06-22 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_curso_modulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='portada',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='url_portada_respaldo',
        ),
        migrations.AddField(
            model_name='curso',
            name='icono',
            field=models.CharField(default='bi-music-note', max_length=50),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('teoria', 'Teoría Musical'), ('auditivo', 'Entrenamiento Auditivo'), ('instrumento', 'Instrumento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('progreso', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscritos', to='web.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
    ]
