
# Generated by Django 4.2.30 on 2026-07-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_perfil_avatar_perfil_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='banner',
        ),
    ]
