# Generated by Django 4.2.30 on 2026-08-05 22:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 5, 22, 53, 53, 288091, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('teoria', '🎵 Teoría Musical'), ('auditivo', '👂 Entrenamiento Auditivo'), ('instrumento', '🎸 Instrumento')], default='teoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='icono',
            field=models.CharField(default='bi-book', max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('basico', '🟢 Básico'), ('intermedio', '🟠 Intermedio'), ('avanzado', '🔴 Avanzado')], default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
