# Generated by Django 4.2.30 on 2026-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_curso_creado_por_curso_fecha_creacion_curso_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='modulo',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
