# Generated by Django 4.2.30 on 2026-08-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
