# Generated by Django 4.2.30 on 2026-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_perfil_banner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcioncurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='InscripcionCurso',
        ),
        migrations.DeleteModel(
            name='Modulo',
        ),
    ]
