# Generated by Django 4.2.30 on 2026-09-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clase', '0014_clase_activa'),
        ('web', '0016_alter_inscripcioncurso_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('promedio_final', models.DecimalField(decimal_places=1, max_digits=3)),
                ('progreso_final', models.PositiveIntegerField(default=100)),
                ('horas_completadas', models.PositiveIntegerField(default=0)),
                ('codigo_verificacion', models.CharField(max_length=50, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('activo', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='clase.clase')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
                'unique_together': {('estudiante', 'clase')},
            },
        ),
    ]
