# Generated by Django 4.2.30 on 2026-06-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_actividad_pregunta_opcion_respuestaestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clases/'),
        ),
    ]
