# Generated by Django 4.2.30 on 2026-07-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0005_clase_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
