# Generated by Django 4.2.30 on 2026-07-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_actividad_fecha_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='actividad',
        ),
        migrations.AlterUniqueTogether(
            name='respuestaestudiante',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='opcion',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='pregunta',
        ),
        migrations.AlterUniqueTogether(
            name='solicitudclase',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solicitudclase',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='solicitudclase',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Anuncio',
        ),
        migrations.DeleteModel(
            name='Clase',
        ),
        migrations.DeleteModel(
            name='Leccion',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='RespuestaEstudiante',
        ),
        migrations.DeleteModel(
            name='SolicitudClase',
        ),
    ]
