# Generated by Django 4.2.30 on 2026-07-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='calificacion_maxima',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='actividad',
            name='calificacion_minima',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='intentos_desde_cero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='max_estudiantes',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='clase',
            name='nivel_previo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_siguiente', to='clase.clase'),
        ),
    ]
