# Generated by Django 4.2.30 on 2026-08-01 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_actividad_calificacion_maxima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='max_estudiantes',
            field=models.PositiveIntegerField(default=35, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(35)]),
        ),
    ]
