# Generated by Django 4.2.30 on 2026-08-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0004_inscripcionnivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionnivel',
            name='nivel',
            field=models.CharField(choices=[('1', '1 - Bajo'), ('2', '2 - Medio'), ('3', '3 - Intermedio'), ('4', '4 - Experto')], default='1', max_length=10),
        ),
    ]
