# Generated by Django 4.2.30 on 2026-08-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0005_alter_inscripcionnivel_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='categoria_tema',
            field=models.CharField(choices=[('armonia', 'Armonía'), ('ritmo', 'Ritmo'), ('melodia', 'Melodía')], default='armonia', max_length=20),
        ),
    ]
