# Generated by Django 4.2.30 on 2026-08-12 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clase', '0006_clase_categoria_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_tema', models.CharField(max_length=100)),
                ('intentos', models.PositiveIntegerField(default=1)),
                ('bloqueado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veces_inscrito', models.PositiveIntegerField(default=1)),
                ('bloqueado', models.BooleanField(default=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clase.clase')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('estudiante', 'clase')},
            },
        ),
    ]
