# Generated by Django 4.2.30 on 2026-08-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0007_historialinscripcion_inscripcionclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudclase',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitudclase',
            name='intentos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
