# Generated by Django 4.2.30 on 2026-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0008_solicitudclase_bloqueado_solicitudclase_intentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcionnivel',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='leccion',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='actividad',
        ),
        migrations.AlterUniqueTogether(
            name='respuestaestudiante',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='opcion',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='InscripcionNivel',
        ),
        migrations.DeleteModel(
            name='Leccion',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='RespuestaEstudiante',
        ),
    ]
