# Generated by Django 4.2.30 on 2026-09-07 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clase', '0009_remove_inscripcionnivel_estudiante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('audio', 'Audio'), ('partitura', 'Partitura'), ('video', 'Video'), ('documento', 'Documento'), ('imagen', 'Imagen')], default='documento', max_length=20)),
                ('categoria', models.CharField(choices=[('intervalos', 'Intervalos'), ('acordes', 'Acordes'), ('escalas', 'Escalas'), ('ritmo', 'Ritmo'), ('melodia', 'Melodía'), ('armonia', 'Armonía'), ('teoria', 'Teoría Musical'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('url_externa', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso Musical',
                'verbose_name_plural': 'Recursos Musicales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
