# Generated by Django 4.2.30 on 2026-09-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0010_recursomusical'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecursoMusical',
        ),
    ]
