# Generated by Django 4.2.30 on 2026-09-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0011_delete_recursomusical'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
