# Generated by Django 4.2.30 on 2026-09-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0012_clase_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='activo',
        ),
    ]
