# Generated by Django 4.2.30 on 2026-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0013_remove_clase_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si está desactivada, los estudiantes no pueden acceder aunque la fecha esté vigente.', verbose_name='Clase activa'),
        ),
    ]
